Fix build against gcc 5.4
When building against gcc 5.4. link error occurs:

CMakeFiles/build_correctness_func_clone.dir/correctness/func_clone.cpp.o:
In function `Halide::Internal::IRVisitor::IRVisitor()':
func_clone.cpp:(.text._ZN6Halide8Internal9IRVisitorC2Ev[_ZN6Halide8Internal9IRVisitorC5Ev]+0x9):
  undefined reference to `vtable for Halide::Internal::IRVisitor'

The reason is the compiler selected to generate a default constructor of
IRVisitor/... inside func_clone.cpp.o because we did not provide one.
But it does not generates a vtable for IRVisitor/... in func_clone.cpp.o
I don't know why the compiler optimize away the vtable.

The way to fix the issue is to explicitly define the constructor.
So there will be only one constructor inside libHalide.so and
func_clone.cpp.o will not contain IRVisitor::IRVisitor(), just simply
linked the constructor inside libHalide.so


Former-commit-id: 4fdc7461ab0d345dd693069caf5bba2cf7606638 [formerly fcaf933977383ab50878fb0bac5ad9b7acb48fd6]
Former-commit-id: 89a89b7e8bed23d9326768723b9597e12ff24f19