Fix build with clang trunk - mainly -Wrange-loop-construct issues
All these otherwise result in diagnostics like:
```
[1/844 0.8/sec] Building CXX object src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o
FAILED: src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o
/usr/local/bin/clang++  -DCOMPILING_HALIDE -DHalide_EXPORTS -DHalide_SHARED -DLLVM_VERSION=90 -DNDEBUG -DWITH_AARCH64 -DWITH_AMDGPU -DWITH_ARM -DWITH_D3D12 -DWITH_HEXAGON -DWITH_METAL -DWITH_MIPS -DWITH_OPENCL -DWITH_OPENGL -DWITH_POWERPC -DWITH_PTX -DWITH_RISCV -DWITH_X86 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/lib/llvm-9/include -O2 -g  -fPIC   -Wall -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Woverloaded-virtual -Werror -std=c++11 -MD -MT src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o -MF src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o.d -o src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o -c /repositories/Halide/src/AddImageChecks.cpp
/repositories/Halide/src/AddImageChecks.cpp:159:51: error: loop variable 'buf' has type 'const pair<std::string, FindBuffers::Result> &' (aka 'const pair<basic_string<char>, Halide::Internal::FindBuffers::Result> &') but is initialized with type 'std::pair<const std::__cxx11::basic_string<char>, Halide::Internal::FindBuffers::Result>' resulting in a copy [-Werror,-Wrange-loop-construct]
    for (const pair<string, FindBuffers::Result> &buf : bufs) {
                                                  ^
/repositories/Halide/src/AddImageChecks.cpp:159:10: note: use non-reference type 'pair<std::string, FindBuffers::Result>' (aka 'pair<basic_string<char>, Halide::Internal::FindBuffers::Result>') to keep the copy or type 'const std::pair<const std::__cxx11::basic_string<char>, Halide::Internal::FindBuffers::Result> &' to prevent copying
    for (const pair<string, FindBuffers::Result> &buf : bufs) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
With this patch the master builds warning-free with clang trunk again.